// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpM9-U7CXHZkCEEaPJQasYhN5UniRGNxs',
    appId: '1:832838758052:web:c29401ab75756117d38031',
    messagingSenderId: '832838758052',
    projectId: 'bajaj-app-2e3e1',
    authDomain: 'bajaj-app-2e3e1.firebaseapp.com',
    storageBucket: 'bajaj-app-2e3e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiwuOR4EaDjx1xzKv_uDpjE7FroIkAWo',
    appId: '1:832838758052:android:3df84adba51149f7d38031',
    messagingSenderId: '832838758052',
    projectId: 'bajaj-app-2e3e1',
    storageBucket: 'bajaj-app-2e3e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAmVAvnrFiGmem5NaX9G7tMtvEb3K0mE',
    appId: '1:832838758052:ios:4ddb8d1dd82374d2d38031',
    messagingSenderId: '832838758052',
    projectId: 'bajaj-app-2e3e1',
    storageBucket: 'bajaj-app-2e3e1.firebasestorage.app',
    iosBundleId: 'com.example.bajajApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACAmVAvnrFiGmem5NaX9G7tMtvEb3K0mE',
    appId: '1:832838758052:ios:4ddb8d1dd82374d2d38031',
    messagingSenderId: '832838758052',
    projectId: 'bajaj-app-2e3e1',
    storageBucket: 'bajaj-app-2e3e1.firebasestorage.app',
    iosBundleId: 'com.example.bajajApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpM9-U7CXHZkCEEaPJQasYhN5UniRGNxs',
    appId: '1:832838758052:web:1db20ed8580c2246d38031',
    messagingSenderId: '832838758052',
    projectId: 'bajaj-app-2e3e1',
    authDomain: 'bajaj-app-2e3e1.firebaseapp.com',
    storageBucket: 'bajaj-app-2e3e1.firebasestorage.app',
  );
}
